// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmokeTube.Models;

namespace SmokeTube.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmokeTube.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("Name");

                    b.Property<int?>("PokurId");

                    b.HasKey("Id");

                    b.HasIndex("PokurId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SmokeTube.Models.Pokur", b =>
                {
                    b.Property<int>("PokurId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfTobacco");

                    b.Property<string>("NameOfTobacco");

                    b.Property<decimal>("PriceOfTobacco");

                    b.HasKey("PokurId");

                    b.ToTable("Pokurs");
                });

            modelBuilder.Entity("SmokeTube.Models.Member", b =>
                {
                    b.HasOne("SmokeTube.Models.Pokur")
                        .WithMany("Members")
                        .HasForeignKey("PokurId");
                });
#pragma warning restore 612, 618
        }
    }
}
